---
deployment:
  tasks:
    - echo "===== Iniciando deploy de Laravel + Vue ====="

    - export COMPOSER_HOME="$HOME/.composer"

    - echo "No hay shell disponible, se asume que vendor y public/build ya están en el repo"

    - echo "Deploy automático: copiando archivos al Deploy Path"
    - cp -r repositories/sistema-ventas/* sistemas/demosistemaventas/sistema-ventas/

    - echo "===== Deploy finalizado para demo sistema ====="
